name: Build and Push Docker Image

on:
  push:
    branches:
      - master
    paths:
      - '17-3.5/**'
      - '.github/workflows/docker-build-and-push.yml'
  pull_request:
    paths:
      - '17-3.5/**'
      - '.github/workflows/docker-build-and-push.yml'
  release:
    types: [published]


jobs:
  docker:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Set up Docker
        uses: docker/setup-docker-action@v4

      - name: Build image
        run: docker build -t postgis -f 17-3.5/Dockerfile ./17-3.5/

      - name: Log in to Docker Hub
        if: startsWith(github.ref, 'refs/tags/')
        uses: docker/login-action@v3
        with:
          username: ${{ vars.DOCKER_USER }}
          password: ${{ secrets.DOCKER_PAT }}

      - name: Set up Docker Buildx
        if: startsWith(github.ref, 'refs/tags/')
        uses: docker/setup-buildx-action@v3
        with:
          driver: cloud
          endpoint: "eseidinger/github"
          platforms: linux/amd64,linux/arm64
          install: true

      - name: Build and push
        id: build-docker
        if: startsWith(github.ref, 'refs/tags/')
        uses: docker/build-push-action@v6
        with:
          tags: "${{ vars.DOCKER_USER }}/postgis:latest,${{ vars.DOCKER_USER }}/postgis:${{ github.ref_name }}"
          # For pull requests, export results to the build cache.
          # Otherwise, push to a registry.
          outputs: ${{ github.event_name == 'pull_request' && 'type=cacheonly' || 'type=registry' }}
          context: ./17-3.5
          file: ./17-3.5/Dockerfile
          platforms: linux/amd64,linux/arm64
